// Central Ant Design theme — Oxford Blue design system (matches placement portal).
// Passed to <ConfigProvider theme={antdTheme}> at the app root.

export const brand = {
  primary:       "#14213D",
  primaryHover:  "#1C2C4F",
  primaryActive: "#0B1526",
  accent:        "#7C2D3E",
  accentHover:   "#932F42",
  ink:           "#161B22",
  bodyText:      "#33383F",
  muted:         "#666B72",
  border:        "#E4E1E0",
  surface:       "#FFFFFF",
  layoutBg:      "#F4F2F1",
  tintHover:     "#F1EDEA",
  tintActive:    "#E9E2DF",
};

export const antdTheme = {
  token: {
    colorPrimary:          brand.primary,
    colorInfo:             brand.accent,
    colorLink:             brand.accent,
    colorLinkHover:        brand.accentHover,
    colorTextBase:         brand.ink,
    colorText:             brand.bodyText,
    colorTextSecondary:    brand.muted,
    colorBorder:           brand.border,
    colorBorderSecondary:  "#EDF0F5",
    colorBgLayout:         brand.layoutBg,
    borderRadius:          0,
    borderRadiusLG:        0,
    borderRadiusSM:        0,
    borderRadiusXS:        0,
    borderRadiusOuter:     0,
    wireframe:             false,
    fontFamily:            "'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Helvetica Neue', Arial, sans-serif",
    fontSize:              14,
    controlHeight:         38,
    boxShadowSecondary:    "0 6px 16px -8px rgba(15,23,42,0.14), 0 3px 6px -4px rgba(15,23,42,0.10)",
  },
  components: {
    Button: {
      colorPrimaryHover: brand.primaryHover,
      colorPrimaryActive: brand.primaryActive,
      primaryShadow: "none",
      fontWeight: 600,
      controlHeight: 38,
      borderRadius: 0,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
    },
    Table: {
      headerBg:         "#F1F4F9",
      headerColor:      brand.ink,
      headerSplitColor: "transparent",
      rowHoverBg:       "#F5F8FD",
      borderColor:      "#EDF0F5",
      cellPaddingBlock: 12,
      borderRadiusLG:   0,
    },
    Card: {
      borderRadiusLG:        0,
      headerBg:              "transparent",
      colorBorderSecondary:  brand.border,
    },
    Input: {
      controlHeight: 38,
      activeShadow:  "0 0 0 2px rgba(27,38,59,0.12)",
      borderRadius:  0,
      borderRadiusLG: 0,
      borderRadiusSM: 0,
    },
    Select: {
      controlHeight:      38,
      borderRadius:       0,
      borderRadiusLG:     0,
      borderRadiusSM:     0,
      optionActiveBg:     brand.tintHover,
      optionSelectedBg:   brand.tintActive,
      optionSelectedColor: brand.primary,
    },
    Tabs: {
      inkBarColor:      brand.primary,
      itemSelectedColor: brand.primary,
      itemHoverColor:   brand.primaryHover,
      titleFontSize:    14,
    },
    Menu: {
      itemSelectedBg:   brand.tintActive,
      itemSelectedColor: brand.primary,
      itemHoverColor:   brand.primary,
      itemHoverBg:      brand.tintHover,
      itemHeight:       42,
      iconSize:         18,
      itemBorderRadius: 0,
    },
    Modal:    { borderRadiusLG: 0, titleFontSize: 18 },
    Tag:      { borderRadiusSM: 0 },
    Segmented: {
      itemSelectedBg:    brand.primary,
      itemSelectedColor: "#FFFFFF",
      trackBg:           "#EAEEF4",
      borderRadius:      0,
      borderRadiusSM:    0,
    },
    Progress: { defaultColor: brand.primary },
    Avatar:   { borderRadius: 0 },
    Dropdown: { borderRadiusLG: 0 },
    Alert:    { borderRadiusLG: 0 },
    Popover:  { borderRadiusLG: 0 },
    Tooltip:  { borderRadius: 0 },
  },
};

export default antdTheme;
